### ISSUE TITLE
How do I play?

### ISSUE THREAD

**Issue by adamMcneil** [lukemcneil/killer-queen#1]
How do you play?

**Comment by lukemcneil** [comment]
Good point. I'll add a readme, but you join with a controller by pressing R1, L1, R2, or L2. Can't play with keyboard, should probably add that.

**Comment by lukemcneil** [comment]
Added a readme in https://github.com/lukemcneil/killer-queen/commit/dcdbae55a3bd19ca62848519008f797eeba88ae1.
